import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Aside from "@/components/Aside";
import QueryProvider from "@/util/providers/QueryProvider";
import { useAuth } from "@/store/authStore";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const cookieStore = cookies();
  // const token = cookieStore.get("auth-token");

  // console.log("Token en RootLayout:", token);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <NavBar />
          <div className="bg-slate-50 min-h-screen flex">
            {/* Sidebar para pantallas grandes */}
            <Aside />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
